# Generated by Django 6.0.3 on 2026-03-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='group',
        ),
        migrations.AddField(
            model_name='stream',
            name='groups',
            field=models.ManyToManyField(related_name='streams', to='university.group'),
        ),
    ]
