# Generated by Django 6.0.3 on 2026-03-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_remove_stream_group_stream_groups'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stream',
            name='unique_stream_per_lecture_group_subgroup',
        ),
    ]
