# Generated by Django 6.0.3 on 2026-03-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_stream_unique_stream_per_lecture_group_subgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='groups',
            new_name='group',
        ),
    ]
