# Generated by Django 6.0.3 on 2026-03-15 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_rename_groups_stream_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='week_type',
            field=models.CharField(choices=[('every', 'Каждую неделю'), ('numerator', 'Числитель'), ('denominator', 'Знаменатель')], default='every', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timeslot',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='schedules',
                to='university.timeslot',
            ),
            preserve_default=False,
        ),
    ]
