# Generated by Django 6.0.3 on 2026-03-16 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_subject_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='university.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='specialty',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialties', to='university.chair'),
        ),
        migrations.AddField(
            model_name='subject',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='university.chair'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='university.chair'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='university.chair'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('chair', 'name'), name='unique_subject_per_chair'),
        ),
        migrations.AddConstraint(
            model_name='chair',
            constraint=models.UniqueConstraint(fields=('faculty', 'name'), name='unique_chair_per_faculty'),
        ),
    ]
