# Generated by Django 6.0.3 on 2026-03-16 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_remove_subject_faculty_chair_specialty_chair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='credits',
            field=models.PositiveIntegerField(verbose_name='Количество кредитов'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='hours',
            field=models.PositiveIntegerField(verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.term', verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная')], max_length=20, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='group',
            field=models.ManyToManyField(related_name='streams', to='university.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.lecture', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='max_budget',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мест (бюджет)'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='max_contract',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мест (контракт)'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('full', 'Заполнен')], default='closed', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='subgroup',
            field=models.IntegerField(choices=[(0, 'Вся группа'), (1, 'Подгруппа 1'), (2, 'Подгруппа 2')], default=0, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название дисциплины'),
        ),
    ]
