# Generated by Django 6.0.3 on 2026-03-18 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_alter_lecture_credits_alter_lecture_hours_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='progressinstudy',
            name='unique_progress_per_student_lecture',
        ),
        migrations.RemoveField(
            model_name='gradecontrol',
            name='lecture',
        ),
        migrations.AddField(
            model_name='gradecontrol',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_controls', to='university.subject'),
        ),
        migrations.AddField(
            model_name='gradecontrol',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_controls', to='university.term'),
        ),
        migrations.AddField(
            model_name='progressinstudy',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.subject'),
        ),
        migrations.AddField(
            model_name='progressinstudy',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.term'),
        ),
        migrations.RemoveField(
            model_name='progressinstudy',
            name='lecture',
        ),
    ]
